"""Add caregiver_email to CaregiverAssignment

Revision ID: 9b848d777426
Revises: 1f798403f8ec
Create Date: 2026-08-15 09:16:23.198110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b848d777426'
down_revision: Union[str, Sequence[str], None] = '1f798403f8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caregiver_assignments', sa.Column('caregiver_email', sa.String(), nullable=True))
    op.alter_column('caregiver_assignments', 'caregiver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('ca_user_caregiver_unique'), 'caregiver_assignments', type_='unique')
    op.drop_index(op.f('idx_caregiver_assignments_active'), table_name='caregiver_assignments')
    op.drop_index(op.f('idx_caregiver_assignments_caregiver'), table_name='caregiver_assignments')
    op.drop_index(op.f('idx_caregiver_assignments_user'), table_name='caregiver_assignments')
    op.create_index(op.f('ix_caregiver_assignments_caregiver_email'), 'caregiver_assignments', ['caregiver_email'], unique=False)
    op.create_index(op.f('ix_caregiver_assignments_caregiver_id'), 'caregiver_assignments', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_caregiver_assignments_id'), 'caregiver_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_caregiver_assignments_user_id'), 'caregiver_assignments', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_ca_user'), 'caregiver_assignments', type_='foreignkey')
    op.drop_constraint(op.f('fk_ca_caregiver'), 'caregiver_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'caregiver_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'caregiver_assignments', 'users', ['caregiver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'caregiver_assignments', type_='foreignkey')
    op.drop_constraint(None, 'caregiver_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ca_caregiver'), 'caregiver_assignments', 'users', ['caregiver_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ca_user'), 'caregiver_assignments', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_caregiver_assignments_user_id'), table_name='caregiver_assignments')
    op.drop_index(op.f('ix_caregiver_assignments_id'), table_name='caregiver_assignments')
    op.drop_index(op.f('ix_caregiver_assignments_caregiver_id'), table_name='caregiver_assignments')
    op.drop_index(op.f('ix_caregiver_assignments_caregiver_email'), table_name='caregiver_assignments')
    op.create_index(op.f('idx_caregiver_assignments_user'), 'caregiver_assignments', ['user_id'], unique=False)
    op.create_index(op.f('idx_caregiver_assignments_caregiver'), 'caregiver_assignments', ['caregiver_id'], unique=False)
    op.create_index(op.f('idx_caregiver_assignments_active'), 'caregiver_assignments', ['user_id', 'caregiver_id', 'status'], unique=False)
    op.create_unique_constraint(op.f('ca_user_caregiver_unique'), 'caregiver_assignments', ['user_id', 'caregiver_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('caregiver_assignments', 'caregiver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('caregiver_assignments', 'caregiver_email')
    # ### end Alembic commands ###
